version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.12-rc
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq_stream advertised_host localhost
    ports:
      # AMQP protocol port
      - 5672:5672
      # AMQP protocol port stream
      - 5552:5552
      # HTTP management UI
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge